// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyvdUueDeWbXgwVHmBYeCcT05TcTkrr0',
    appId: '1:126589555743:web:f1d0bbba9fc3a39871712a',
    messagingSenderId: '126589555743',
    projectId: 'aasaanflutter',
    authDomain: 'aasaanflutter.firebaseapp.com',
    storageBucket: 'aasaanflutter.firebasestorage.app',
    measurementId: 'G-9TWTVBQVDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-XxKuTjOxD1GKXAlrOQNmdrbqu32MmA',
    appId: '1:126589555743:android:e52543ee5bce5e8a71712a',
    messagingSenderId: '126589555743',
    projectId: 'aasaanflutter',
    storageBucket: 'aasaanflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bDzDJ_sdluMcw_qYBNDBmWP8rxU52F8',
    appId: '1:126589555743:ios:0e09ca2a18fea7aa71712a',
    messagingSenderId: '126589555743',
    projectId: 'aasaanflutter',
    storageBucket: 'aasaanflutter.firebasestorage.app',
    iosBundleId: 'com.mindtech.aasaan.aasaanFlutter',
  );
}
